/**
 * generated by Xtext
 */
package co.edu.uniandes.csw.spl.dsl.serializer;

import co.edu.uniandes.csw.spl.dsl.serializer.AbstractMVCDslSemanticSequencer;

@SuppressWarnings("all")
public class MVCDslSemanticSequencer extends AbstractMVCDslSemanticSequencer {
}
