/**
 * generated by Xtext
 */
package co.edu.uniandes.csw.dsl.serializer;

import co.edu.uniandes.csw.dsl.serializer.AbstractEntitiesSemanticSequencer;

@SuppressWarnings("all")
public class EntitiesSemanticSequencer extends AbstractEntitiesSemanticSequencer {
}
