/*
* generated by Xtext
*/
package co.edu.uniandes.csw.spl.dsl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class MVCDslStandaloneSetup extends MVCDslStandaloneSetupGenerated{

	public static void doSetup() {
		new MVCDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

