/*
* generated by Xtext
*/
package co.edu.uniandes.csw.dsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ComponentAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("co/edu/uniandes/csw/dsl/parser/antlr/internal/InternalComponent.tokens");
	}
}
