/**
 * generated by Xtext
 */
package co.edu.uniandes.csw.dsl.serializer;

import co.edu.uniandes.csw.dsl.serializer.AbstractComponentSyntacticSequencer;

@SuppressWarnings("all")
public class ComponentSyntacticSequencer extends AbstractComponentSyntacticSequencer {
}
