/**
 * generated by Xtext
 */
package co.edu.uniandes.csw.dsl.serializer;

import co.edu.uniandes.csw.dsl.serializer.AbstractComponentSemanticSequencer;

@SuppressWarnings("all")
public class ComponentSemanticSequencer extends AbstractComponentSemanticSequencer {
}
