/*
* generated by Xtext
*/
package co.edu.uniandes.csw.spl.dsl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import co.edu.uniandes.csw.spl.dsl.services.AnnotateitGrammarAccess;

public class AnnotateitParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private AnnotateitGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected co.edu.uniandes.csw.spl.dsl.parser.antlr.internal.InternalAnnotateitParser createParser(XtextTokenStream stream) {
		return new co.edu.uniandes.csw.spl.dsl.parser.antlr.internal.InternalAnnotateitParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Package";
	}
	
	public AnnotateitGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(AnnotateitGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
