/**
 * generated by Xtext
 */
package co.edu.uniandes.csw.spl.dsl.serializer;

import co.edu.uniandes.csw.spl.dsl.serializer.AbstractAnnotateitSyntacticSequencer;

@SuppressWarnings("all")
public class AnnotateitSyntacticSequencer extends AbstractAnnotateitSyntacticSequencer {
}
