/**
 * generated by Xtext
 */
package co.edu.uniandes.csw.dsl.validation;

import co.edu.uniandes.csw.dsl.validation.AbstractComponentValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class ComponentValidator extends AbstractComponentValidator {
}
