/*
* generated by Xtext
*/
package co.edu.uniandes.csw.dsl.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import co.edu.uniandes.csw.dsl.services.EntitiesGrammarAccess;

public class EntitiesParser extends AbstractContentAssistParser {
	
	@Inject
	private EntitiesGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected co.edu.uniandes.csw.dsl.ui.contentassist.antlr.internal.InternalEntitiesParser createParser() {
		co.edu.uniandes.csw.dsl.ui.contentassist.antlr.internal.InternalEntitiesParser result = new co.edu.uniandes.csw.dsl.ui.contentassist.antlr.internal.InternalEntitiesParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getEntitiesAccess().getGroup(), "rule__Entities__Group__0");
					put(grammarAccess.getImportsAccess().getGroup(), "rule__Imports__Group__0");
					put(grammarAccess.getAnnotationAccess().getGroup(), "rule__Annotation__Group__0");
					put(grammarAccess.getAnnotationAccess().getGroup_3(), "rule__Annotation__Group_3__0");
					put(grammarAccess.getAnnotationAccess().getGroup_3_1(), "rule__Annotation__Group_3_1__0");
					put(grammarAccess.getEntityAccess().getGroup(), "rule__Entity__Group__0");
					put(grammarAccess.getEntityAccess().getGroup_4(), "rule__Entity__Group_4__0");
					put(grammarAccess.getEntityAccess().getGroup_4_3(), "rule__Entity__Group_4_3__0");
					put(grammarAccess.getEntityAccess().getGroup_6(), "rule__Entity__Group_6__0");
					put(grammarAccess.getEntityAccess().getGroup_6_1(), "rule__Entity__Group_6_1__0");
					put(grammarAccess.getEntityAccess().getGroup_7(), "rule__Entity__Group_7__0");
					put(grammarAccess.getEntityAccess().getGroup_7_3(), "rule__Entity__Group_7_3__0");
					put(grammarAccess.getAnnotationAttributeAccess().getGroup(), "rule__AnnotationAttribute__Group__0");
					put(grammarAccess.getSimpleValueAccess().getGroup(), "rule__SimpleValue__Group__0");
					put(grammarAccess.getAttributeAccess().getGroup(), "rule__Attribute__Group__0");
					put(grammarAccess.getAssociationAccess().getGroup(), "rule__Association__Group__0");
					put(grammarAccess.getAssociationAccess().getGroup_6(), "rule__Association__Group_6__0");
					put(grammarAccess.getAssociationAccess().getGroup_6_0(), "rule__Association__Group_6_0__0");
					put(grammarAccess.getAssociationAccess().getGroup_6_2(), "rule__Association__Group_6_2__0");
					put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
					put(grammarAccess.getEntitiesAccess().getImportsAssignment_1(), "rule__Entities__ImportsAssignment_1");
					put(grammarAccess.getEntitiesAccess().getEntitiesAssignment_2(), "rule__Entities__EntitiesAssignment_2");
					put(grammarAccess.getImportsAccess().getImportURIAssignment_1(), "rule__Imports__ImportURIAssignment_1");
					put(grammarAccess.getAnnotationAccess().getAnnotationTypeAssignment_1(), "rule__Annotation__AnnotationTypeAssignment_1");
					put(grammarAccess.getAnnotationAccess().getAttributesAssignment_3_0(), "rule__Annotation__AttributesAssignment_3_0");
					put(grammarAccess.getAnnotationAccess().getAttributesAssignment_3_1_1(), "rule__Annotation__AttributesAssignment_3_1_1");
					put(grammarAccess.getEntityAccess().getAnnotationsAssignment_1(), "rule__Entity__AnnotationsAssignment_1");
					put(grammarAccess.getEntityAccess().getNameAssignment_3(), "rule__Entity__NameAssignment_3");
					put(grammarAccess.getEntityAccess().getExtendsAssignment_4_2(), "rule__Entity__ExtendsAssignment_4_2");
					put(grammarAccess.getEntityAccess().getExtendsAssignment_4_3_1(), "rule__Entity__ExtendsAssignment_4_3_1");
					put(grammarAccess.getEntityAccess().getAttributesAssignment_6_0(), "rule__Entity__AttributesAssignment_6_0");
					put(grammarAccess.getEntityAccess().getAttributesAssignment_6_1_1(), "rule__Entity__AttributesAssignment_6_1_1");
					put(grammarAccess.getEntityAccess().getAssociationsAssignment_7_2(), "rule__Entity__AssociationsAssignment_7_2");
					put(grammarAccess.getEntityAccess().getAssociationsAssignment_7_3_1(), "rule__Entity__AssociationsAssignment_7_3_1");
					put(grammarAccess.getAnnotationAttributeAccess().getAttributeAssignment_0(), "rule__AnnotationAttribute__AttributeAssignment_0");
					put(grammarAccess.getAnnotationAttributeAccess().getValueAssignment_2(), "rule__AnnotationAttribute__ValueAssignment_2");
					put(grammarAccess.getSimpleValueAccess().getValueAssignment_1(), "rule__SimpleValue__ValueAssignment_1");
					put(grammarAccess.getAttributeAccess().getAnnotationsAssignment_1(), "rule__Attribute__AnnotationsAssignment_1");
					put(grammarAccess.getAttributeAccess().getNameAssignment_2(), "rule__Attribute__NameAssignment_2");
					put(grammarAccess.getAttributeAccess().getTypeAssignment_4(), "rule__Attribute__TypeAssignment_4");
					put(grammarAccess.getAssociationAccess().getContainmentAssignment_0(), "rule__Association__ContainmentAssignment_0");
					put(grammarAccess.getAssociationAccess().getAnnotationsAssignment_1(), "rule__Association__AnnotationsAssignment_1");
					put(grammarAccess.getAssociationAccess().getNameAssignment_3(), "rule__Association__NameAssignment_3");
					put(grammarAccess.getAssociationAccess().getTargetAssignment_5(), "rule__Association__TargetAssignment_5");
					put(grammarAccess.getAssociationAccess().getLowerBoundAssignment_6_0_1(), "rule__Association__LowerBoundAssignment_6_0_1");
					put(grammarAccess.getAssociationAccess().getUpperBoundAssignment_6_2_1(), "rule__Association__UpperBoundAssignment_6_2_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			co.edu.uniandes.csw.dsl.ui.contentassist.antlr.internal.InternalEntitiesParser typedParser = (co.edu.uniandes.csw.dsl.ui.contentassist.antlr.internal.InternalEntitiesParser) parser;
			typedParser.entryRuleEntities();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public EntitiesGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(EntitiesGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
