/*
 * generated by Xtext
 */
package co.edu.uniandes.csw.spl.dsl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import co.edu.uniandes.csw.spl.dsl.ui.internal.MVCDslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MVCDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return MVCDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return MVCDslActivator.getInstance().getInjector(MVCDslActivator.CO_EDU_UNIANDES_CSW_SPL_DSL_MVCDSL);
	}
	
}
