/*
* generated by Xtext
*/
package co.edu.uniandes.csw.dsl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class ComponentUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return co.edu.uniandes.csw.dsl.ui.internal.ComponentActivator.getInstance().getInjector("co.edu.uniandes.csw.dsl.Component");
	}
	
}
