/*
* generated by Xtext
*/
package co.edu.uniandes.csw.dsl.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class ComponentGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class ComponentElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Component");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cComponentAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cImportsAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cImportsImportParserRuleCall_1_0 = (RuleCall)cImportsAssignment_1.eContents().get(0);
		private final Assignment cAnnotationsAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cAnnotationsAnnotationParserRuleCall_2_0 = (RuleCall)cAnnotationsAssignment_2.eContents().get(0);
		private final Keyword cComponentKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cNameAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cNameIDTerminalRuleCall_4_0 = (RuleCall)cNameAssignment_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cModelsKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cModelsAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final RuleCall cModelsModelParserRuleCall_6_2_0 = (RuleCall)cModelsAssignment_6_2.eContents().get(0);
		private final Group cGroup_6_3 = (Group)cGroup_6.eContents().get(3);
		private final Keyword cCommaKeyword_6_3_0 = (Keyword)cGroup_6_3.eContents().get(0);
		private final Assignment cModelsAssignment_6_3_1 = (Assignment)cGroup_6_3.eContents().get(1);
		private final RuleCall cModelsModelParserRuleCall_6_3_1_0 = (RuleCall)cModelsAssignment_6_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6_4 = (Keyword)cGroup_6.eContents().get(4);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cViewsKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cViewsAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final RuleCall cViewsViewParserRuleCall_7_2_0 = (RuleCall)cViewsAssignment_7_2.eContents().get(0);
		private final Group cGroup_7_3 = (Group)cGroup_7.eContents().get(3);
		private final Keyword cCommaKeyword_7_3_0 = (Keyword)cGroup_7_3.eContents().get(0);
		private final Assignment cViewsAssignment_7_3_1 = (Assignment)cGroup_7_3.eContents().get(1);
		private final RuleCall cViewsViewParserRuleCall_7_3_1_0 = (RuleCall)cViewsAssignment_7_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7_4 = (Keyword)cGroup_7.eContents().get(4);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cEventsKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_8_1 = (Keyword)cGroup_8.eContents().get(1);
		private final Assignment cEventsAssignment_8_2 = (Assignment)cGroup_8.eContents().get(2);
		private final RuleCall cEventsEventParserRuleCall_8_2_0 = (RuleCall)cEventsAssignment_8_2.eContents().get(0);
		private final Group cGroup_8_3 = (Group)cGroup_8.eContents().get(3);
		private final Keyword cCommaKeyword_8_3_0 = (Keyword)cGroup_8_3.eContents().get(0);
		private final Assignment cEventsAssignment_8_3_1 = (Assignment)cGroup_8_3.eContents().get(1);
		private final RuleCall cEventsEventParserRuleCall_8_3_1_0 = (RuleCall)cEventsAssignment_8_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8_4 = (Keyword)cGroup_8.eContents().get(4);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cControllersKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_9_1 = (Keyword)cGroup_9.eContents().get(1);
		private final Assignment cControllersAssignment_9_2 = (Assignment)cGroup_9.eContents().get(2);
		private final RuleCall cControllersControllerParserRuleCall_9_2_0 = (RuleCall)cControllersAssignment_9_2.eContents().get(0);
		private final Group cGroup_9_3 = (Group)cGroup_9.eContents().get(3);
		private final Keyword cCommaKeyword_9_3_0 = (Keyword)cGroup_9_3.eContents().get(0);
		private final Assignment cControllersAssignment_9_3_1 = (Assignment)cGroup_9_3.eContents().get(1);
		private final RuleCall cControllersControllerParserRuleCall_9_3_1_0 = (RuleCall)cControllersAssignment_9_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_9_4 = (Keyword)cGroup_9.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_10 = (Keyword)cGroup.eContents().get(10);
		
		//Component returns mvc::Component:
		//	{mvc::Component} imports+=Import* annotations+=Annotation? "Component" name=ID "{" ("models" "{" models+=Model (","
		//	models+=Model)* "}")? ("views" "{" views+=View ("," views+=View)* "}")? ("events" "{" events+=Event (","
		//	events+=Event)* "}")? ("controllers" "{" controllers+=Controller ("," controllers+=Controller)* "}")? "}";
		public ParserRule getRule() { return rule; }

		//{mvc::Component} imports+=Import* annotations+=Annotation? "Component" name=ID "{" ("models" "{" models+=Model (","
		//models+=Model)* "}")? ("views" "{" views+=View ("," views+=View)* "}")? ("events" "{" events+=Event (","
		//events+=Event)* "}")? ("controllers" "{" controllers+=Controller ("," controllers+=Controller)* "}")? "}"
		public Group getGroup() { return cGroup; }

		//{mvc::Component}
		public Action getComponentAction_0() { return cComponentAction_0; }

		//imports+=Import*
		public Assignment getImportsAssignment_1() { return cImportsAssignment_1; }

		//Import
		public RuleCall getImportsImportParserRuleCall_1_0() { return cImportsImportParserRuleCall_1_0; }

		//annotations+=Annotation?
		public Assignment getAnnotationsAssignment_2() { return cAnnotationsAssignment_2; }

		//Annotation
		public RuleCall getAnnotationsAnnotationParserRuleCall_2_0() { return cAnnotationsAnnotationParserRuleCall_2_0; }

		//"Component"
		public Keyword getComponentKeyword_3() { return cComponentKeyword_3; }

		//name=ID
		public Assignment getNameAssignment_4() { return cNameAssignment_4; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_4_0() { return cNameIDTerminalRuleCall_4_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_5() { return cLeftCurlyBracketKeyword_5; }

		//("models" "{" models+=Model ("," models+=Model)* "}")?
		public Group getGroup_6() { return cGroup_6; }

		//"models"
		public Keyword getModelsKeyword_6_0() { return cModelsKeyword_6_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_6_1() { return cLeftCurlyBracketKeyword_6_1; }

		//models+=Model
		public Assignment getModelsAssignment_6_2() { return cModelsAssignment_6_2; }

		//Model
		public RuleCall getModelsModelParserRuleCall_6_2_0() { return cModelsModelParserRuleCall_6_2_0; }

		//("," models+=Model)*
		public Group getGroup_6_3() { return cGroup_6_3; }

		//","
		public Keyword getCommaKeyword_6_3_0() { return cCommaKeyword_6_3_0; }

		//models+=Model
		public Assignment getModelsAssignment_6_3_1() { return cModelsAssignment_6_3_1; }

		//Model
		public RuleCall getModelsModelParserRuleCall_6_3_1_0() { return cModelsModelParserRuleCall_6_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6_4() { return cRightCurlyBracketKeyword_6_4; }

		//("views" "{" views+=View ("," views+=View)* "}")?
		public Group getGroup_7() { return cGroup_7; }

		//"views"
		public Keyword getViewsKeyword_7_0() { return cViewsKeyword_7_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_7_1() { return cLeftCurlyBracketKeyword_7_1; }

		//views+=View
		public Assignment getViewsAssignment_7_2() { return cViewsAssignment_7_2; }

		//View
		public RuleCall getViewsViewParserRuleCall_7_2_0() { return cViewsViewParserRuleCall_7_2_0; }

		//("," views+=View)*
		public Group getGroup_7_3() { return cGroup_7_3; }

		//","
		public Keyword getCommaKeyword_7_3_0() { return cCommaKeyword_7_3_0; }

		//views+=View
		public Assignment getViewsAssignment_7_3_1() { return cViewsAssignment_7_3_1; }

		//View
		public RuleCall getViewsViewParserRuleCall_7_3_1_0() { return cViewsViewParserRuleCall_7_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_7_4() { return cRightCurlyBracketKeyword_7_4; }

		//("events" "{" events+=Event ("," events+=Event)* "}")?
		public Group getGroup_8() { return cGroup_8; }

		//"events"
		public Keyword getEventsKeyword_8_0() { return cEventsKeyword_8_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_8_1() { return cLeftCurlyBracketKeyword_8_1; }

		//events+=Event
		public Assignment getEventsAssignment_8_2() { return cEventsAssignment_8_2; }

		//Event
		public RuleCall getEventsEventParserRuleCall_8_2_0() { return cEventsEventParserRuleCall_8_2_0; }

		//("," events+=Event)*
		public Group getGroup_8_3() { return cGroup_8_3; }

		//","
		public Keyword getCommaKeyword_8_3_0() { return cCommaKeyword_8_3_0; }

		//events+=Event
		public Assignment getEventsAssignment_8_3_1() { return cEventsAssignment_8_3_1; }

		//Event
		public RuleCall getEventsEventParserRuleCall_8_3_1_0() { return cEventsEventParserRuleCall_8_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_8_4() { return cRightCurlyBracketKeyword_8_4; }

		//("controllers" "{" controllers+=Controller ("," controllers+=Controller)* "}")?
		public Group getGroup_9() { return cGroup_9; }

		//"controllers"
		public Keyword getControllersKeyword_9_0() { return cControllersKeyword_9_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_9_1() { return cLeftCurlyBracketKeyword_9_1; }

		//controllers+=Controller
		public Assignment getControllersAssignment_9_2() { return cControllersAssignment_9_2; }

		//Controller
		public RuleCall getControllersControllerParserRuleCall_9_2_0() { return cControllersControllerParserRuleCall_9_2_0; }

		//("," controllers+=Controller)*
		public Group getGroup_9_3() { return cGroup_9_3; }

		//","
		public Keyword getCommaKeyword_9_3_0() { return cCommaKeyword_9_3_0; }

		//controllers+=Controller
		public Assignment getControllersAssignment_9_3_1() { return cControllersAssignment_9_3_1; }

		//Controller
		public RuleCall getControllersControllerParserRuleCall_9_3_1_0() { return cControllersControllerParserRuleCall_9_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_9_4() { return cRightCurlyBracketKeyword_9_4; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_10() { return cRightCurlyBracketKeyword_10; }
	}

	public class ImportElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Import");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cImportKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cImportURIAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cImportURISTRINGTerminalRuleCall_1_0 = (RuleCall)cImportURIAssignment_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//Import returns mvc::Import:
		//	"import" importURI=STRING ";";
		public ParserRule getRule() { return rule; }

		//"import" importURI=STRING ";"
		public Group getGroup() { return cGroup; }

		//"import"
		public Keyword getImportKeyword_0() { return cImportKeyword_0; }

		//importURI=STRING
		public Assignment getImportURIAssignment_1() { return cImportURIAssignment_1; }

		//STRING
		public RuleCall getImportURISTRINGTerminalRuleCall_1_0() { return cImportURISTRINGTerminalRuleCall_1_0; }

		//";"
		public Keyword getSemicolonKeyword_2() { return cSemicolonKeyword_2; }
	}

	public class AnnotationAttributeValueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "AnnotationAttributeValue");
		private final RuleCall cSimpleValueParserRuleCall = (RuleCall)rule.eContents().get(1);
		
		//AnnotationAttributeValue:
		//	SimpleValue;
		public ParserRule getRule() { return rule; }

		//SimpleValue
		public RuleCall getSimpleValueParserRuleCall() { return cSimpleValueParserRuleCall; }
	}

	public class UIComponentElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "UIComponent");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cUILayoutParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cUIInputParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cUIActionsParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cUILabelParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		
		//UIComponent returns mvc::UIComponent:
		//	UILayout | UIInput | UIActions | UILabel;
		public ParserRule getRule() { return rule; }

		//UILayout | UIInput | UIActions | UILabel
		public Alternatives getAlternatives() { return cAlternatives; }

		//UILayout
		public RuleCall getUILayoutParserRuleCall_0() { return cUILayoutParserRuleCall_0; }

		//UIInput
		public RuleCall getUIInputParserRuleCall_1() { return cUIInputParserRuleCall_1; }

		//UIActions
		public RuleCall getUIActionsParserRuleCall_2() { return cUIActionsParserRuleCall_2; }

		//UILabel
		public RuleCall getUILabelParserRuleCall_3() { return cUILabelParserRuleCall_3; }
	}

	public class UILayoutElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "UILayout");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLayoutKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cComponentsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cComponentsUIComponentParserRuleCall_3_0 = (RuleCall)cComponentsAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//UILayout returns mvc::UILayout:
		//	"layout" name=ID "{" components+=UIComponent+ "}";
		public ParserRule getRule() { return rule; }

		//"layout" name=ID "{" components+=UIComponent+ "}"
		public Group getGroup() { return cGroup; }

		//"layout"
		public Keyword getLayoutKeyword_0() { return cLayoutKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//components+=UIComponent+
		public Assignment getComponentsAssignment_3() { return cComponentsAssignment_3; }

		//UIComponent
		public RuleCall getComponentsUIComponentParserRuleCall_3_0() { return cComponentsUIComponentParserRuleCall_3_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}

	public class AnnotationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Annotation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCommercialAtKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cAnnotationTypeAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cAnnotationTypeAnnotationTypeCrossReference_1_0 = (CrossReference)cAnnotationTypeAssignment_1.eContents().get(0);
		private final RuleCall cAnnotationTypeAnnotationTypeIDTerminalRuleCall_1_0_1 = (RuleCall)cAnnotationTypeAnnotationTypeCrossReference_1_0.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Assignment cAttributesAssignment_3_0 = (Assignment)cGroup_3.eContents().get(0);
		private final RuleCall cAttributesAnnotationAttributeParserRuleCall_3_0_0 = (RuleCall)cAttributesAssignment_3_0.eContents().get(0);
		private final Group cGroup_3_1 = (Group)cGroup_3.eContents().get(1);
		private final Keyword cCommaKeyword_3_1_0 = (Keyword)cGroup_3_1.eContents().get(0);
		private final Assignment cAttributesAssignment_3_1_1 = (Assignment)cGroup_3_1.eContents().get(1);
		private final RuleCall cAttributesAnnotationAttributeParserRuleCall_3_1_1_0 = (RuleCall)cAttributesAssignment_3_1_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Annotation:
		//	"@" annotationType=[AnnotationType] "(" (attributes+=AnnotationAttribute ("," attributes+=AnnotationAttribute)*)?
		//	")";
		public ParserRule getRule() { return rule; }

		//"@" annotationType=[AnnotationType] "(" (attributes+=AnnotationAttribute ("," attributes+=AnnotationAttribute)*)? ")"
		public Group getGroup() { return cGroup; }

		//"@"
		public Keyword getCommercialAtKeyword_0() { return cCommercialAtKeyword_0; }

		//annotationType=[AnnotationType]
		public Assignment getAnnotationTypeAssignment_1() { return cAnnotationTypeAssignment_1; }

		//[AnnotationType]
		public CrossReference getAnnotationTypeAnnotationTypeCrossReference_1_0() { return cAnnotationTypeAnnotationTypeCrossReference_1_0; }

		//ID
		public RuleCall getAnnotationTypeAnnotationTypeIDTerminalRuleCall_1_0_1() { return cAnnotationTypeAnnotationTypeIDTerminalRuleCall_1_0_1; }

		//"("
		public Keyword getLeftParenthesisKeyword_2() { return cLeftParenthesisKeyword_2; }

		//(attributes+=AnnotationAttribute ("," attributes+=AnnotationAttribute)*)?
		public Group getGroup_3() { return cGroup_3; }

		//attributes+=AnnotationAttribute
		public Assignment getAttributesAssignment_3_0() { return cAttributesAssignment_3_0; }

		//AnnotationAttribute
		public RuleCall getAttributesAnnotationAttributeParserRuleCall_3_0_0() { return cAttributesAnnotationAttributeParserRuleCall_3_0_0; }

		//("," attributes+=AnnotationAttribute)*
		public Group getGroup_3_1() { return cGroup_3_1; }

		//","
		public Keyword getCommaKeyword_3_1_0() { return cCommaKeyword_3_1_0; }

		//attributes+=AnnotationAttribute
		public Assignment getAttributesAssignment_3_1_1() { return cAttributesAssignment_3_1_1; }

		//AnnotationAttribute
		public RuleCall getAttributesAnnotationAttributeParserRuleCall_3_1_1_0() { return cAttributesAnnotationAttributeParserRuleCall_3_1_1_0; }

		//")"
		public Keyword getRightParenthesisKeyword_4() { return cRightParenthesisKeyword_4; }
	}

	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Model");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cModelAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cAnnotationsAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cAnnotationsAnnotationParserRuleCall_1_0 = (RuleCall)cAnnotationsAssignment_1.eContents().get(0);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cColonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cRootEntityAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final CrossReference cRootEntityEntityCrossReference_4_0 = (CrossReference)cRootEntityAssignment_4.eContents().get(0);
		private final RuleCall cRootEntityEntityIDTerminalRuleCall_4_0_1 = (RuleCall)cRootEntityEntityCrossReference_4_0.eContents().get(1);
		private final Keyword cSemicolonKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Model returns mvc::Model:
		//	{mvc::Model} annotations+=Annotation? name=ID ":" rootEntity=[mvc::Entity]? ";";
		public ParserRule getRule() { return rule; }

		//{mvc::Model} annotations+=Annotation? name=ID ":" rootEntity=[mvc::Entity]? ";"
		public Group getGroup() { return cGroup; }

		//{mvc::Model}
		public Action getModelAction_0() { return cModelAction_0; }

		//annotations+=Annotation?
		public Assignment getAnnotationsAssignment_1() { return cAnnotationsAssignment_1; }

		//Annotation
		public RuleCall getAnnotationsAnnotationParserRuleCall_1_0() { return cAnnotationsAnnotationParserRuleCall_1_0; }

		//name=ID
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_2_0() { return cNameIDTerminalRuleCall_2_0; }

		//":"
		public Keyword getColonKeyword_3() { return cColonKeyword_3; }

		//rootEntity=[mvc::Entity]?
		public Assignment getRootEntityAssignment_4() { return cRootEntityAssignment_4; }

		//[mvc::Entity]
		public CrossReference getRootEntityEntityCrossReference_4_0() { return cRootEntityEntityCrossReference_4_0; }

		//ID
		public RuleCall getRootEntityEntityIDTerminalRuleCall_4_0_1() { return cRootEntityEntityIDTerminalRuleCall_4_0_1; }

		//";"
		public Keyword getSemicolonKeyword_5() { return cSemicolonKeyword_5; }
	}

	public class ViewElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "View");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cViewAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cAnnotationsAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cAnnotationsAnnotationParserRuleCall_1_0 = (RuleCall)cAnnotationsAssignment_1.eContents().get(0);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cRootComponentAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cRootComponentUILayoutParserRuleCall_4_0 = (RuleCall)cRootComponentAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//View returns mvc::View:
		//	{mvc::View} annotations+=Annotation? name=ID "{" rootComponent=UILayout "}";
		public ParserRule getRule() { return rule; }

		//{mvc::View} annotations+=Annotation? name=ID "{" rootComponent=UILayout "}"
		public Group getGroup() { return cGroup; }

		//{mvc::View}
		public Action getViewAction_0() { return cViewAction_0; }

		//annotations+=Annotation?
		public Assignment getAnnotationsAssignment_1() { return cAnnotationsAssignment_1; }

		//Annotation
		public RuleCall getAnnotationsAnnotationParserRuleCall_1_0() { return cAnnotationsAnnotationParserRuleCall_1_0; }

		//name=ID
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_2_0() { return cNameIDTerminalRuleCall_2_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }

		//rootComponent=UILayout
		public Assignment getRootComponentAssignment_4() { return cRootComponentAssignment_4; }

		//UILayout
		public RuleCall getRootComponentUILayoutParserRuleCall_4_0() { return cRootComponentUILayoutParserRuleCall_4_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}

	public class EventElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Event");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cEventAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cAnnotationsAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cAnnotationsAnnotationParserRuleCall_1_0 = (RuleCall)cAnnotationsAssignment_1.eContents().get(0);
		private final Keyword cEventKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cNameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cNameSTRINGTerminalRuleCall_3_0 = (RuleCall)cNameAssignment_3.eContents().get(0);
		private final Keyword cSemicolonKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Event returns mvc::Event:
		//	{mvc::Event} annotations+=Annotation? "Event" name=STRING ";";
		public ParserRule getRule() { return rule; }

		//{mvc::Event} annotations+=Annotation? "Event" name=STRING ";"
		public Group getGroup() { return cGroup; }

		//{mvc::Event}
		public Action getEventAction_0() { return cEventAction_0; }

		//annotations+=Annotation?
		public Assignment getAnnotationsAssignment_1() { return cAnnotationsAssignment_1; }

		//Annotation
		public RuleCall getAnnotationsAnnotationParserRuleCall_1_0() { return cAnnotationsAnnotationParserRuleCall_1_0; }

		//"Event"
		public Keyword getEventKeyword_2() { return cEventKeyword_2; }

		//name=STRING
		public Assignment getNameAssignment_3() { return cNameAssignment_3; }

		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_3_0() { return cNameSTRINGTerminalRuleCall_3_0; }

		//";"
		public Keyword getSemicolonKeyword_4() { return cSemicolonKeyword_4; }
	}

	public class ControllerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Controller");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cControllerAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cAnnotationsAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cAnnotationsAnnotationParserRuleCall_1_0 = (RuleCall)cAnnotationsAssignment_1.eContents().get(0);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cActionsKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cActionsAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cActionsActionParserRuleCall_4_2_0 = (RuleCall)cActionsAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cActionsAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cActionsActionParserRuleCall_4_3_1_0 = (RuleCall)cActionsAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cViewsKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cViewsAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cViewsControllerViewParserRuleCall_5_2_0 = (RuleCall)cViewsAssignment_5_2.eContents().get(0);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cViewsAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final RuleCall cViewsControllerViewParserRuleCall_5_3_1_0 = (RuleCall)cViewsAssignment_5_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cEventActionsKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cEventActionsAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final RuleCall cEventActionsEventActionParserRuleCall_6_2_0 = (RuleCall)cEventActionsAssignment_6_2.eContents().get(0);
		private final Group cGroup_6_3 = (Group)cGroup_6.eContents().get(3);
		private final Keyword cCommaKeyword_6_3_0 = (Keyword)cGroup_6_3.eContents().get(0);
		private final Assignment cEventActionsAssignment_6_3_1 = (Assignment)cGroup_6_3.eContents().get(1);
		private final RuleCall cEventActionsEventActionParserRuleCall_6_3_1_0 = (RuleCall)cEventActionsAssignment_6_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6_4 = (Keyword)cGroup_6.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Controller returns mvc::Controller:
		//	{mvc::Controller} annotations+=Annotation? name=ID "{" ("actions" "{" actions+=Action ("," actions+=Action)* "}")?
		//	("views" "{" views+=ControllerView ("," views+=ControllerView)* "}")? ("eventActions" "{" eventActions+=EventAction
		//	("," eventActions+=EventAction)* "}")? "}";
		public ParserRule getRule() { return rule; }

		//{mvc::Controller} annotations+=Annotation? name=ID "{" ("actions" "{" actions+=Action ("," actions+=Action)* "}")?
		//("views" "{" views+=ControllerView ("," views+=ControllerView)* "}")? ("eventActions" "{" eventActions+=EventAction
		//("," eventActions+=EventAction)* "}")? "}"
		public Group getGroup() { return cGroup; }

		//{mvc::Controller}
		public Action getControllerAction_0() { return cControllerAction_0; }

		//annotations+=Annotation?
		public Assignment getAnnotationsAssignment_1() { return cAnnotationsAssignment_1; }

		//Annotation
		public RuleCall getAnnotationsAnnotationParserRuleCall_1_0() { return cAnnotationsAnnotationParserRuleCall_1_0; }

		//name=ID
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_2_0() { return cNameIDTerminalRuleCall_2_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }

		//("actions" "{" actions+=Action ("," actions+=Action)* "}")?
		public Group getGroup_4() { return cGroup_4; }

		//"actions"
		public Keyword getActionsKeyword_4_0() { return cActionsKeyword_4_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }

		//actions+=Action
		public Assignment getActionsAssignment_4_2() { return cActionsAssignment_4_2; }

		//Action
		public RuleCall getActionsActionParserRuleCall_4_2_0() { return cActionsActionParserRuleCall_4_2_0; }

		//("," actions+=Action)*
		public Group getGroup_4_3() { return cGroup_4_3; }

		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }

		//actions+=Action
		public Assignment getActionsAssignment_4_3_1() { return cActionsAssignment_4_3_1; }

		//Action
		public RuleCall getActionsActionParserRuleCall_4_3_1_0() { return cActionsActionParserRuleCall_4_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }

		//("views" "{" views+=ControllerView ("," views+=ControllerView)* "}")?
		public Group getGroup_5() { return cGroup_5; }

		//"views"
		public Keyword getViewsKeyword_5_0() { return cViewsKeyword_5_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_5_1() { return cLeftCurlyBracketKeyword_5_1; }

		//views+=ControllerView
		public Assignment getViewsAssignment_5_2() { return cViewsAssignment_5_2; }

		//ControllerView
		public RuleCall getViewsControllerViewParserRuleCall_5_2_0() { return cViewsControllerViewParserRuleCall_5_2_0; }

		//("," views+=ControllerView)*
		public Group getGroup_5_3() { return cGroup_5_3; }

		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }

		//views+=ControllerView
		public Assignment getViewsAssignment_5_3_1() { return cViewsAssignment_5_3_1; }

		//ControllerView
		public RuleCall getViewsControllerViewParserRuleCall_5_3_1_0() { return cViewsControllerViewParserRuleCall_5_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5_4() { return cRightCurlyBracketKeyword_5_4; }

		//("eventActions" "{" eventActions+=EventAction ("," eventActions+=EventAction)* "}")?
		public Group getGroup_6() { return cGroup_6; }

		//"eventActions"
		public Keyword getEventActionsKeyword_6_0() { return cEventActionsKeyword_6_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_6_1() { return cLeftCurlyBracketKeyword_6_1; }

		//eventActions+=EventAction
		public Assignment getEventActionsAssignment_6_2() { return cEventActionsAssignment_6_2; }

		//EventAction
		public RuleCall getEventActionsEventActionParserRuleCall_6_2_0() { return cEventActionsEventActionParserRuleCall_6_2_0; }

		//("," eventActions+=EventAction)*
		public Group getGroup_6_3() { return cGroup_6_3; }

		//","
		public Keyword getCommaKeyword_6_3_0() { return cCommaKeyword_6_3_0; }

		//eventActions+=EventAction
		public Assignment getEventActionsAssignment_6_3_1() { return cEventActionsAssignment_6_3_1; }

		//EventAction
		public RuleCall getEventActionsEventActionParserRuleCall_6_3_1_0() { return cEventActionsEventActionParserRuleCall_6_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6_4() { return cRightCurlyBracketKeyword_6_4; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}

	public class AnnotationAttributeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "AnnotationAttribute");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cAttributeAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cAttributeAnnotationTypeAttributeCrossReference_0_0 = (CrossReference)cAttributeAssignment_0.eContents().get(0);
		private final RuleCall cAttributeAnnotationTypeAttributeIDTerminalRuleCall_0_0_1 = (RuleCall)cAttributeAnnotationTypeAttributeCrossReference_0_0.eContents().get(1);
		private final Keyword cEqualsSignKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cValueAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cValueAnnotationAttributeValueParserRuleCall_2_0 = (RuleCall)cValueAssignment_2.eContents().get(0);
		
		//AnnotationAttribute:
		//	attribute=[AnnotationTypeAttribute] "=" value=AnnotationAttributeValue;
		public ParserRule getRule() { return rule; }

		//attribute=[AnnotationTypeAttribute] "=" value=AnnotationAttributeValue
		public Group getGroup() { return cGroup; }

		//attribute=[AnnotationTypeAttribute]
		public Assignment getAttributeAssignment_0() { return cAttributeAssignment_0; }

		//[AnnotationTypeAttribute]
		public CrossReference getAttributeAnnotationTypeAttributeCrossReference_0_0() { return cAttributeAnnotationTypeAttributeCrossReference_0_0; }

		//ID
		public RuleCall getAttributeAnnotationTypeAttributeIDTerminalRuleCall_0_0_1() { return cAttributeAnnotationTypeAttributeIDTerminalRuleCall_0_0_1; }

		//"="
		public Keyword getEqualsSignKeyword_1() { return cEqualsSignKeyword_1; }

		//value=AnnotationAttributeValue
		public Assignment getValueAssignment_2() { return cValueAssignment_2; }

		//AnnotationAttributeValue
		public RuleCall getValueAnnotationAttributeValueParserRuleCall_2_0() { return cValueAnnotationAttributeValueParserRuleCall_2_0; }
	}

	public class SimpleValueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "SimpleValue");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cSimpleValueAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cValueAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cValueSTRINGTerminalRuleCall_1_0 = (RuleCall)cValueAssignment_1.eContents().get(0);
		
		//SimpleValue:
		//	{SimpleValue} value=STRING;
		public ParserRule getRule() { return rule; }

		//{SimpleValue} value=STRING
		public Group getGroup() { return cGroup; }

		//{SimpleValue}
		public Action getSimpleValueAction_0() { return cSimpleValueAction_0; }

		//value=STRING
		public Assignment getValueAssignment_1() { return cValueAssignment_1; }

		//STRING
		public RuleCall getValueSTRINGTerminalRuleCall_1_0() { return cValueSTRINGTerminalRuleCall_1_0; }
	}

	public class UIInputElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "UIInput");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cUIInputAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cAnnotationsAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cAnnotationsAnnotationParserRuleCall_1_0 = (RuleCall)cAnnotationsAssignment_1.eContents().get(0);
		private final Keyword cInputKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cNameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cNameIDTerminalRuleCall_3_0 = (RuleCall)cNameAssignment_3.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cTypeKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cTypeAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cTypeIDTerminalRuleCall_5_1_0 = (RuleCall)cTypeAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cValueKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cValueAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final CrossReference cValueAttributeCrossReference_6_1_0 = (CrossReference)cValueAssignment_6_1.eContents().get(0);
		private final RuleCall cValueAttributeIDTerminalRuleCall_6_1_0_1 = (RuleCall)cValueAttributeCrossReference_6_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//UIInput returns mvc::UIInput:
		//	{mvc::UIInput} annotations+=Annotation? "input" name=ID "{" ("type" type=ID)? ("value" value=[mvc::Attribute])? "}";
		public ParserRule getRule() { return rule; }

		//{mvc::UIInput} annotations+=Annotation? "input" name=ID "{" ("type" type=ID)? ("value" value=[mvc::Attribute])? "}"
		public Group getGroup() { return cGroup; }

		//{mvc::UIInput}
		public Action getUIInputAction_0() { return cUIInputAction_0; }

		//annotations+=Annotation?
		public Assignment getAnnotationsAssignment_1() { return cAnnotationsAssignment_1; }

		//Annotation
		public RuleCall getAnnotationsAnnotationParserRuleCall_1_0() { return cAnnotationsAnnotationParserRuleCall_1_0; }

		//"input"
		public Keyword getInputKeyword_2() { return cInputKeyword_2; }

		//name=ID
		public Assignment getNameAssignment_3() { return cNameAssignment_3; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_3_0() { return cNameIDTerminalRuleCall_3_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_4() { return cLeftCurlyBracketKeyword_4; }

		//("type" type=ID)?
		public Group getGroup_5() { return cGroup_5; }

		//"type"
		public Keyword getTypeKeyword_5_0() { return cTypeKeyword_5_0; }

		//type=ID
		public Assignment getTypeAssignment_5_1() { return cTypeAssignment_5_1; }

		//ID
		public RuleCall getTypeIDTerminalRuleCall_5_1_0() { return cTypeIDTerminalRuleCall_5_1_0; }

		//("value" value=[mvc::Attribute])?
		public Group getGroup_6() { return cGroup_6; }

		//"value"
		public Keyword getValueKeyword_6_0() { return cValueKeyword_6_0; }

		//value=[mvc::Attribute]
		public Assignment getValueAssignment_6_1() { return cValueAssignment_6_1; }

		//[mvc::Attribute]
		public CrossReference getValueAttributeCrossReference_6_1_0() { return cValueAttributeCrossReference_6_1_0; }

		//ID
		public RuleCall getValueAttributeIDTerminalRuleCall_6_1_0_1() { return cValueAttributeIDTerminalRuleCall_6_1_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}

	public class UIActionsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "UIActions");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cUIActionsAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cAnnotationsAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cAnnotationsAnnotationParserRuleCall_1_0 = (RuleCall)cAnnotationsAssignment_1.eContents().get(0);
		private final Keyword cActionKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cNameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cNameIDTerminalRuleCall_3_0 = (RuleCall)cNameAssignment_3.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cTypeKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cTypeAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cTypeSTRINGTerminalRuleCall_5_1_0 = (RuleCall)cTypeAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cTriggerEventKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cTriggerEventAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final CrossReference cTriggerEventEventCrossReference_6_1_0 = (CrossReference)cTriggerEventAssignment_6_1.eContents().get(0);
		private final RuleCall cTriggerEventEventIDTerminalRuleCall_6_1_0_1 = (RuleCall)cTriggerEventEventCrossReference_6_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//UIActions returns mvc::UIActions:
		//	{mvc::UIActions} annotations+=Annotation? "action" name=ID "{" ("type" type=STRING)? ("triggerEvent"
		//	triggerEvent=[mvc::Event])? "}";
		public ParserRule getRule() { return rule; }

		//{mvc::UIActions} annotations+=Annotation? "action" name=ID "{" ("type" type=STRING)? ("triggerEvent"
		//triggerEvent=[mvc::Event])? "}"
		public Group getGroup() { return cGroup; }

		//{mvc::UIActions}
		public Action getUIActionsAction_0() { return cUIActionsAction_0; }

		//annotations+=Annotation?
		public Assignment getAnnotationsAssignment_1() { return cAnnotationsAssignment_1; }

		//Annotation
		public RuleCall getAnnotationsAnnotationParserRuleCall_1_0() { return cAnnotationsAnnotationParserRuleCall_1_0; }

		//"action"
		public Keyword getActionKeyword_2() { return cActionKeyword_2; }

		//name=ID
		public Assignment getNameAssignment_3() { return cNameAssignment_3; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_3_0() { return cNameIDTerminalRuleCall_3_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_4() { return cLeftCurlyBracketKeyword_4; }

		//("type" type=STRING)?
		public Group getGroup_5() { return cGroup_5; }

		//"type"
		public Keyword getTypeKeyword_5_0() { return cTypeKeyword_5_0; }

		//type=STRING
		public Assignment getTypeAssignment_5_1() { return cTypeAssignment_5_1; }

		//STRING
		public RuleCall getTypeSTRINGTerminalRuleCall_5_1_0() { return cTypeSTRINGTerminalRuleCall_5_1_0; }

		//("triggerEvent" triggerEvent=[mvc::Event])?
		public Group getGroup_6() { return cGroup_6; }

		//"triggerEvent"
		public Keyword getTriggerEventKeyword_6_0() { return cTriggerEventKeyword_6_0; }

		//triggerEvent=[mvc::Event]
		public Assignment getTriggerEventAssignment_6_1() { return cTriggerEventAssignment_6_1; }

		//[mvc::Event]
		public CrossReference getTriggerEventEventCrossReference_6_1_0() { return cTriggerEventEventCrossReference_6_1_0; }

		//ID
		public RuleCall getTriggerEventEventIDTerminalRuleCall_6_1_0_1() { return cTriggerEventEventIDTerminalRuleCall_6_1_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}

	public class UILabelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "UILabel");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cUILabelAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cAnnotationsAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cAnnotationsAnnotationParserRuleCall_1_0 = (RuleCall)cAnnotationsAssignment_1.eContents().get(0);
		private final Keyword cLabelKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cNameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cNameIDTerminalRuleCall_3_0 = (RuleCall)cNameAssignment_3.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cTypeKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cTypeAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cTypeSTRINGTerminalRuleCall_5_1_0 = (RuleCall)cTypeAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cTextKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cTextAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cTextSTRINGTerminalRuleCall_6_1_0 = (RuleCall)cTextAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cValueKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cValueAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final CrossReference cValueAttributeCrossReference_7_1_0 = (CrossReference)cValueAssignment_7_1.eContents().get(0);
		private final RuleCall cValueAttributeIDTerminalRuleCall_7_1_0_1 = (RuleCall)cValueAttributeCrossReference_7_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//UILabel returns mvc::UILabel:
		//	{mvc::UILabel} annotations+=Annotation? "label" name=ID "{" ("type" type=STRING)? ("text" text=STRING)? ("value"
		//	value=[mvc::Attribute])? "}";
		public ParserRule getRule() { return rule; }

		//{mvc::UILabel} annotations+=Annotation? "label" name=ID "{" ("type" type=STRING)? ("text" text=STRING)? ("value"
		//value=[mvc::Attribute])? "}"
		public Group getGroup() { return cGroup; }

		//{mvc::UILabel}
		public Action getUILabelAction_0() { return cUILabelAction_0; }

		//annotations+=Annotation?
		public Assignment getAnnotationsAssignment_1() { return cAnnotationsAssignment_1; }

		//Annotation
		public RuleCall getAnnotationsAnnotationParserRuleCall_1_0() { return cAnnotationsAnnotationParserRuleCall_1_0; }

		//"label"
		public Keyword getLabelKeyword_2() { return cLabelKeyword_2; }

		//name=ID
		public Assignment getNameAssignment_3() { return cNameAssignment_3; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_3_0() { return cNameIDTerminalRuleCall_3_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_4() { return cLeftCurlyBracketKeyword_4; }

		//("type" type=STRING)?
		public Group getGroup_5() { return cGroup_5; }

		//"type"
		public Keyword getTypeKeyword_5_0() { return cTypeKeyword_5_0; }

		//type=STRING
		public Assignment getTypeAssignment_5_1() { return cTypeAssignment_5_1; }

		//STRING
		public RuleCall getTypeSTRINGTerminalRuleCall_5_1_0() { return cTypeSTRINGTerminalRuleCall_5_1_0; }

		//("text" text=STRING)?
		public Group getGroup_6() { return cGroup_6; }

		//"text"
		public Keyword getTextKeyword_6_0() { return cTextKeyword_6_0; }

		//text=STRING
		public Assignment getTextAssignment_6_1() { return cTextAssignment_6_1; }

		//STRING
		public RuleCall getTextSTRINGTerminalRuleCall_6_1_0() { return cTextSTRINGTerminalRuleCall_6_1_0; }

		//("value" value=[mvc::Attribute])?
		public Group getGroup_7() { return cGroup_7; }

		//"value"
		public Keyword getValueKeyword_7_0() { return cValueKeyword_7_0; }

		//value=[mvc::Attribute]
		public Assignment getValueAssignment_7_1() { return cValueAssignment_7_1; }

		//[mvc::Attribute]
		public CrossReference getValueAttributeCrossReference_7_1_0() { return cValueAttributeCrossReference_7_1_0; }

		//ID
		public RuleCall getValueAttributeIDTerminalRuleCall_7_1_0_1() { return cValueAttributeIDTerminalRuleCall_7_1_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}

	public class ActionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Action");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cActionAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cAnnotationsAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cAnnotationsAnnotationParserRuleCall_1_0 = (RuleCall)cAnnotationsAssignment_1.eContents().get(0);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cPreExecutionEventKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cPreExecutionEventAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final CrossReference cPreExecutionEventEventCrossReference_4_1_0 = (CrossReference)cPreExecutionEventAssignment_4_1.eContents().get(0);
		private final RuleCall cPreExecutionEventEventIDTerminalRuleCall_4_1_0_1 = (RuleCall)cPreExecutionEventEventCrossReference_4_1_0.eContents().get(1);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cPostExecutionEventKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cPostExecutionEventAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final CrossReference cPostExecutionEventEventCrossReference_5_1_0 = (CrossReference)cPostExecutionEventAssignment_5_1.eContents().get(0);
		private final RuleCall cPostExecutionEventEventIDTerminalRuleCall_5_1_0_1 = (RuleCall)cPostExecutionEventEventCrossReference_5_1_0.eContents().get(1);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cTriggerEventsKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cTriggerEventsAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final CrossReference cTriggerEventsEventCrossReference_6_2_0 = (CrossReference)cTriggerEventsAssignment_6_2.eContents().get(0);
		private final RuleCall cTriggerEventsEventIDTerminalRuleCall_6_2_0_1 = (RuleCall)cTriggerEventsEventCrossReference_6_2_0.eContents().get(1);
		private final Group cGroup_6_3 = (Group)cGroup_6.eContents().get(3);
		private final Keyword cCommaKeyword_6_3_0 = (Keyword)cGroup_6_3.eContents().get(0);
		private final Assignment cTriggerEventsAssignment_6_3_1 = (Assignment)cGroup_6_3.eContents().get(1);
		private final CrossReference cTriggerEventsEventCrossReference_6_3_1_0 = (CrossReference)cTriggerEventsAssignment_6_3_1.eContents().get(0);
		private final RuleCall cTriggerEventsEventIDTerminalRuleCall_6_3_1_0_1 = (RuleCall)cTriggerEventsEventCrossReference_6_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_6_4 = (Keyword)cGroup_6.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Action returns mvc::Action:
		//	{mvc::Action} annotations+=Annotation? name=ID "{" ("preExecutionEvent" preExecutionEvent=[mvc::Event])?
		//	("postExecutionEvent" postExecutionEvent=[mvc::Event])? ("triggerEvents" "(" triggerEvents+=[mvc::Event] (","
		//	triggerEvents+=[mvc::Event])* ")")? "}";
		public ParserRule getRule() { return rule; }

		//{mvc::Action} annotations+=Annotation? name=ID "{" ("preExecutionEvent" preExecutionEvent=[mvc::Event])?
		//("postExecutionEvent" postExecutionEvent=[mvc::Event])? ("triggerEvents" "(" triggerEvents+=[mvc::Event] (","
		//triggerEvents+=[mvc::Event])* ")")? "}"
		public Group getGroup() { return cGroup; }

		//{mvc::Action}
		public Action getActionAction_0() { return cActionAction_0; }

		//annotations+=Annotation?
		public Assignment getAnnotationsAssignment_1() { return cAnnotationsAssignment_1; }

		//Annotation
		public RuleCall getAnnotationsAnnotationParserRuleCall_1_0() { return cAnnotationsAnnotationParserRuleCall_1_0; }

		//name=ID
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_2_0() { return cNameIDTerminalRuleCall_2_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }

		//("preExecutionEvent" preExecutionEvent=[mvc::Event])?
		public Group getGroup_4() { return cGroup_4; }

		//"preExecutionEvent"
		public Keyword getPreExecutionEventKeyword_4_0() { return cPreExecutionEventKeyword_4_0; }

		//preExecutionEvent=[mvc::Event]
		public Assignment getPreExecutionEventAssignment_4_1() { return cPreExecutionEventAssignment_4_1; }

		//[mvc::Event]
		public CrossReference getPreExecutionEventEventCrossReference_4_1_0() { return cPreExecutionEventEventCrossReference_4_1_0; }

		//ID
		public RuleCall getPreExecutionEventEventIDTerminalRuleCall_4_1_0_1() { return cPreExecutionEventEventIDTerminalRuleCall_4_1_0_1; }

		//("postExecutionEvent" postExecutionEvent=[mvc::Event])?
		public Group getGroup_5() { return cGroup_5; }

		//"postExecutionEvent"
		public Keyword getPostExecutionEventKeyword_5_0() { return cPostExecutionEventKeyword_5_0; }

		//postExecutionEvent=[mvc::Event]
		public Assignment getPostExecutionEventAssignment_5_1() { return cPostExecutionEventAssignment_5_1; }

		//[mvc::Event]
		public CrossReference getPostExecutionEventEventCrossReference_5_1_0() { return cPostExecutionEventEventCrossReference_5_1_0; }

		//ID
		public RuleCall getPostExecutionEventEventIDTerminalRuleCall_5_1_0_1() { return cPostExecutionEventEventIDTerminalRuleCall_5_1_0_1; }

		//("triggerEvents" "(" triggerEvents+=[mvc::Event] ("," triggerEvents+=[mvc::Event])* ")")?
		public Group getGroup_6() { return cGroup_6; }

		//"triggerEvents"
		public Keyword getTriggerEventsKeyword_6_0() { return cTriggerEventsKeyword_6_0; }

		//"("
		public Keyword getLeftParenthesisKeyword_6_1() { return cLeftParenthesisKeyword_6_1; }

		//triggerEvents+=[mvc::Event]
		public Assignment getTriggerEventsAssignment_6_2() { return cTriggerEventsAssignment_6_2; }

		//[mvc::Event]
		public CrossReference getTriggerEventsEventCrossReference_6_2_0() { return cTriggerEventsEventCrossReference_6_2_0; }

		//ID
		public RuleCall getTriggerEventsEventIDTerminalRuleCall_6_2_0_1() { return cTriggerEventsEventIDTerminalRuleCall_6_2_0_1; }

		//("," triggerEvents+=[mvc::Event])*
		public Group getGroup_6_3() { return cGroup_6_3; }

		//","
		public Keyword getCommaKeyword_6_3_0() { return cCommaKeyword_6_3_0; }

		//triggerEvents+=[mvc::Event]
		public Assignment getTriggerEventsAssignment_6_3_1() { return cTriggerEventsAssignment_6_3_1; }

		//[mvc::Event]
		public CrossReference getTriggerEventsEventCrossReference_6_3_1_0() { return cTriggerEventsEventCrossReference_6_3_1_0; }

		//ID
		public RuleCall getTriggerEventsEventIDTerminalRuleCall_6_3_1_0_1() { return cTriggerEventsEventIDTerminalRuleCall_6_3_1_0_1; }

		//")"
		public Keyword getRightParenthesisKeyword_6_4() { return cRightParenthesisKeyword_6_4; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}

	public class ControllerViewElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ControllerView");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cAnnotationsAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cAnnotationsAnnotationParserRuleCall_0_0 = (RuleCall)cAnnotationsAssignment_0.eContents().get(0);
		private final Keyword cViewKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cViewAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final CrossReference cViewViewCrossReference_2_0 = (CrossReference)cViewAssignment_2.eContents().get(0);
		private final RuleCall cViewViewIDTerminalRuleCall_2_0_1 = (RuleCall)cViewViewCrossReference_2_0.eContents().get(1);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cModelsKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Assignment cModelsAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final CrossReference cModelsModelCrossReference_3_2_0 = (CrossReference)cModelsAssignment_3_2.eContents().get(0);
		private final RuleCall cModelsModelIDTerminalRuleCall_3_2_0_1 = (RuleCall)cModelsModelCrossReference_3_2_0.eContents().get(1);
		private final Group cGroup_3_3 = (Group)cGroup_3.eContents().get(3);
		private final Keyword cCommaKeyword_3_3_0 = (Keyword)cGroup_3_3.eContents().get(0);
		private final Assignment cModelsAssignment_3_3_1 = (Assignment)cGroup_3_3.eContents().get(1);
		private final CrossReference cModelsModelCrossReference_3_3_1_0 = (CrossReference)cModelsAssignment_3_3_1.eContents().get(0);
		private final RuleCall cModelsModelIDTerminalRuleCall_3_3_1_0_1 = (RuleCall)cModelsModelCrossReference_3_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_3_4 = (Keyword)cGroup_3.eContents().get(4);
		private final Keyword cSemicolonKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//ControllerView returns mvc::ControllerView:
		//	annotations+=Annotation? "view" view=[mvc::View] ("models" "(" models+=[mvc::Model] ("," models+=[mvc::Model])* ")")?
		//	";";
		public ParserRule getRule() { return rule; }

		//annotations+=Annotation? "view" view=[mvc::View] ("models" "(" models+=[mvc::Model] ("," models+=[mvc::Model])* ")")?
		//";"
		public Group getGroup() { return cGroup; }

		//annotations+=Annotation?
		public Assignment getAnnotationsAssignment_0() { return cAnnotationsAssignment_0; }

		//Annotation
		public RuleCall getAnnotationsAnnotationParserRuleCall_0_0() { return cAnnotationsAnnotationParserRuleCall_0_0; }

		//"view"
		public Keyword getViewKeyword_1() { return cViewKeyword_1; }

		//view=[mvc::View]
		public Assignment getViewAssignment_2() { return cViewAssignment_2; }

		//[mvc::View]
		public CrossReference getViewViewCrossReference_2_0() { return cViewViewCrossReference_2_0; }

		//ID
		public RuleCall getViewViewIDTerminalRuleCall_2_0_1() { return cViewViewIDTerminalRuleCall_2_0_1; }

		//("models" "(" models+=[mvc::Model] ("," models+=[mvc::Model])* ")")?
		public Group getGroup_3() { return cGroup_3; }

		//"models"
		public Keyword getModelsKeyword_3_0() { return cModelsKeyword_3_0; }

		//"("
		public Keyword getLeftParenthesisKeyword_3_1() { return cLeftParenthesisKeyword_3_1; }

		//models+=[mvc::Model]
		public Assignment getModelsAssignment_3_2() { return cModelsAssignment_3_2; }

		//[mvc::Model]
		public CrossReference getModelsModelCrossReference_3_2_0() { return cModelsModelCrossReference_3_2_0; }

		//ID
		public RuleCall getModelsModelIDTerminalRuleCall_3_2_0_1() { return cModelsModelIDTerminalRuleCall_3_2_0_1; }

		//("," models+=[mvc::Model])*
		public Group getGroup_3_3() { return cGroup_3_3; }

		//","
		public Keyword getCommaKeyword_3_3_0() { return cCommaKeyword_3_3_0; }

		//models+=[mvc::Model]
		public Assignment getModelsAssignment_3_3_1() { return cModelsAssignment_3_3_1; }

		//[mvc::Model]
		public CrossReference getModelsModelCrossReference_3_3_1_0() { return cModelsModelCrossReference_3_3_1_0; }

		//ID
		public RuleCall getModelsModelIDTerminalRuleCall_3_3_1_0_1() { return cModelsModelIDTerminalRuleCall_3_3_1_0_1; }

		//")"
		public Keyword getRightParenthesisKeyword_3_4() { return cRightParenthesisKeyword_3_4; }

		//";"
		public Keyword getSemicolonKeyword_4() { return cSemicolonKeyword_4; }
	}

	public class EventActionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EventAction");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cAnnotationsAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cAnnotationsAnnotationParserRuleCall_0_0 = (RuleCall)cAnnotationsAssignment_0.eContents().get(0);
		private final Keyword cEventActionKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cActionKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cActionAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final CrossReference cActionActionCrossReference_4_0 = (CrossReference)cActionAssignment_4.eContents().get(0);
		private final RuleCall cActionActionIDTerminalRuleCall_4_0_1 = (RuleCall)cActionActionCrossReference_4_0.eContents().get(1);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cEventsKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cEventsAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final CrossReference cEventsEventCrossReference_5_2_0 = (CrossReference)cEventsAssignment_5_2.eContents().get(0);
		private final RuleCall cEventsEventIDTerminalRuleCall_5_2_0_1 = (RuleCall)cEventsEventCrossReference_5_2_0.eContents().get(1);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cEventsAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final CrossReference cEventsEventCrossReference_5_3_1_0 = (CrossReference)cEventsAssignment_5_3_1.eContents().get(0);
		private final RuleCall cEventsEventIDTerminalRuleCall_5_3_1_0_1 = (RuleCall)cEventsEventCrossReference_5_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//EventAction returns mvc::EventAction:
		//	annotations+=Annotation? "EventAction" "{" "action" action=[mvc::Action] ("events" "(" events+=[mvc::Event] (","
		//	events+=[mvc::Event])* ")")? "}";
		public ParserRule getRule() { return rule; }

		//annotations+=Annotation? "EventAction" "{" "action" action=[mvc::Action] ("events" "(" events+=[mvc::Event] (","
		//events+=[mvc::Event])* ")")? "}"
		public Group getGroup() { return cGroup; }

		//annotations+=Annotation?
		public Assignment getAnnotationsAssignment_0() { return cAnnotationsAssignment_0; }

		//Annotation
		public RuleCall getAnnotationsAnnotationParserRuleCall_0_0() { return cAnnotationsAnnotationParserRuleCall_0_0; }

		//"EventAction"
		public Keyword getEventActionKeyword_1() { return cEventActionKeyword_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//"action"
		public Keyword getActionKeyword_3() { return cActionKeyword_3; }

		//action=[mvc::Action]
		public Assignment getActionAssignment_4() { return cActionAssignment_4; }

		//[mvc::Action]
		public CrossReference getActionActionCrossReference_4_0() { return cActionActionCrossReference_4_0; }

		//ID
		public RuleCall getActionActionIDTerminalRuleCall_4_0_1() { return cActionActionIDTerminalRuleCall_4_0_1; }

		//("events" "(" events+=[mvc::Event] ("," events+=[mvc::Event])* ")")?
		public Group getGroup_5() { return cGroup_5; }

		//"events"
		public Keyword getEventsKeyword_5_0() { return cEventsKeyword_5_0; }

		//"("
		public Keyword getLeftParenthesisKeyword_5_1() { return cLeftParenthesisKeyword_5_1; }

		//events+=[mvc::Event]
		public Assignment getEventsAssignment_5_2() { return cEventsAssignment_5_2; }

		//[mvc::Event]
		public CrossReference getEventsEventCrossReference_5_2_0() { return cEventsEventCrossReference_5_2_0; }

		//ID
		public RuleCall getEventsEventIDTerminalRuleCall_5_2_0_1() { return cEventsEventIDTerminalRuleCall_5_2_0_1; }

		//("," events+=[mvc::Event])*
		public Group getGroup_5_3() { return cGroup_5_3; }

		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }

		//events+=[mvc::Event]
		public Assignment getEventsAssignment_5_3_1() { return cEventsAssignment_5_3_1; }

		//[mvc::Event]
		public CrossReference getEventsEventCrossReference_5_3_1_0() { return cEventsEventCrossReference_5_3_1_0; }

		//ID
		public RuleCall getEventsEventIDTerminalRuleCall_5_3_1_0_1() { return cEventsEventIDTerminalRuleCall_5_3_1_0_1; }

		//")"
		public Keyword getRightParenthesisKeyword_5_4() { return cRightParenthesisKeyword_5_4; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	
	
	private final ComponentElements pComponent;
	private final ImportElements pImport;
	private final AnnotationAttributeValueElements pAnnotationAttributeValue;
	private final UIComponentElements pUIComponent;
	private final UILayoutElements pUILayout;
	private final AnnotationElements pAnnotation;
	private final ModelElements pModel;
	private final ViewElements pView;
	private final EventElements pEvent;
	private final ControllerElements pController;
	private final AnnotationAttributeElements pAnnotationAttribute;
	private final SimpleValueElements pSimpleValue;
	private final UIInputElements pUIInput;
	private final UIActionsElements pUIActions;
	private final UILabelElements pUILabel;
	private final ActionElements pAction;
	private final ControllerViewElements pControllerView;
	private final EventActionElements pEventAction;
	
	private final Grammar grammar;

	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public ComponentGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pComponent = new ComponentElements();
		this.pImport = new ImportElements();
		this.pAnnotationAttributeValue = new AnnotationAttributeValueElements();
		this.pUIComponent = new UIComponentElements();
		this.pUILayout = new UILayoutElements();
		this.pAnnotation = new AnnotationElements();
		this.pModel = new ModelElements();
		this.pView = new ViewElements();
		this.pEvent = new EventElements();
		this.pController = new ControllerElements();
		this.pAnnotationAttribute = new AnnotationAttributeElements();
		this.pSimpleValue = new SimpleValueElements();
		this.pUIInput = new UIInputElements();
		this.pUIActions = new UIActionsElements();
		this.pUILabel = new UILabelElements();
		this.pAction = new ActionElements();
		this.pControllerView = new ControllerViewElements();
		this.pEventAction = new EventActionElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("co.edu.uniandes.csw.dsl.Component".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Component returns mvc::Component:
	//	{mvc::Component} imports+=Import* annotations+=Annotation? "Component" name=ID "{" ("models" "{" models+=Model (","
	//	models+=Model)* "}")? ("views" "{" views+=View ("," views+=View)* "}")? ("events" "{" events+=Event (","
	//	events+=Event)* "}")? ("controllers" "{" controllers+=Controller ("," controllers+=Controller)* "}")? "}";
	public ComponentElements getComponentAccess() {
		return pComponent;
	}
	
	public ParserRule getComponentRule() {
		return getComponentAccess().getRule();
	}

	//Import returns mvc::Import:
	//	"import" importURI=STRING ";";
	public ImportElements getImportAccess() {
		return pImport;
	}
	
	public ParserRule getImportRule() {
		return getImportAccess().getRule();
	}

	//AnnotationAttributeValue:
	//	SimpleValue;
	public AnnotationAttributeValueElements getAnnotationAttributeValueAccess() {
		return pAnnotationAttributeValue;
	}
	
	public ParserRule getAnnotationAttributeValueRule() {
		return getAnnotationAttributeValueAccess().getRule();
	}

	//UIComponent returns mvc::UIComponent:
	//	UILayout | UIInput | UIActions | UILabel;
	public UIComponentElements getUIComponentAccess() {
		return pUIComponent;
	}
	
	public ParserRule getUIComponentRule() {
		return getUIComponentAccess().getRule();
	}

	//UILayout returns mvc::UILayout:
	//	"layout" name=ID "{" components+=UIComponent+ "}";
	public UILayoutElements getUILayoutAccess() {
		return pUILayout;
	}
	
	public ParserRule getUILayoutRule() {
		return getUILayoutAccess().getRule();
	}

	//Annotation:
	//	"@" annotationType=[AnnotationType] "(" (attributes+=AnnotationAttribute ("," attributes+=AnnotationAttribute)*)?
	//	")";
	public AnnotationElements getAnnotationAccess() {
		return pAnnotation;
	}
	
	public ParserRule getAnnotationRule() {
		return getAnnotationAccess().getRule();
	}

	//Model returns mvc::Model:
	//	{mvc::Model} annotations+=Annotation? name=ID ":" rootEntity=[mvc::Entity]? ";";
	public ModelElements getModelAccess() {
		return pModel;
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}

	//View returns mvc::View:
	//	{mvc::View} annotations+=Annotation? name=ID "{" rootComponent=UILayout "}";
	public ViewElements getViewAccess() {
		return pView;
	}
	
	public ParserRule getViewRule() {
		return getViewAccess().getRule();
	}

	//Event returns mvc::Event:
	//	{mvc::Event} annotations+=Annotation? "Event" name=STRING ";";
	public EventElements getEventAccess() {
		return pEvent;
	}
	
	public ParserRule getEventRule() {
		return getEventAccess().getRule();
	}

	//Controller returns mvc::Controller:
	//	{mvc::Controller} annotations+=Annotation? name=ID "{" ("actions" "{" actions+=Action ("," actions+=Action)* "}")?
	//	("views" "{" views+=ControllerView ("," views+=ControllerView)* "}")? ("eventActions" "{" eventActions+=EventAction
	//	("," eventActions+=EventAction)* "}")? "}";
	public ControllerElements getControllerAccess() {
		return pController;
	}
	
	public ParserRule getControllerRule() {
		return getControllerAccess().getRule();
	}

	//AnnotationAttribute:
	//	attribute=[AnnotationTypeAttribute] "=" value=AnnotationAttributeValue;
	public AnnotationAttributeElements getAnnotationAttributeAccess() {
		return pAnnotationAttribute;
	}
	
	public ParserRule getAnnotationAttributeRule() {
		return getAnnotationAttributeAccess().getRule();
	}

	//SimpleValue:
	//	{SimpleValue} value=STRING;
	public SimpleValueElements getSimpleValueAccess() {
		return pSimpleValue;
	}
	
	public ParserRule getSimpleValueRule() {
		return getSimpleValueAccess().getRule();
	}

	//UIInput returns mvc::UIInput:
	//	{mvc::UIInput} annotations+=Annotation? "input" name=ID "{" ("type" type=ID)? ("value" value=[mvc::Attribute])? "}";
	public UIInputElements getUIInputAccess() {
		return pUIInput;
	}
	
	public ParserRule getUIInputRule() {
		return getUIInputAccess().getRule();
	}

	//UIActions returns mvc::UIActions:
	//	{mvc::UIActions} annotations+=Annotation? "action" name=ID "{" ("type" type=STRING)? ("triggerEvent"
	//	triggerEvent=[mvc::Event])? "}";
	public UIActionsElements getUIActionsAccess() {
		return pUIActions;
	}
	
	public ParserRule getUIActionsRule() {
		return getUIActionsAccess().getRule();
	}

	//UILabel returns mvc::UILabel:
	//	{mvc::UILabel} annotations+=Annotation? "label" name=ID "{" ("type" type=STRING)? ("text" text=STRING)? ("value"
	//	value=[mvc::Attribute])? "}";
	public UILabelElements getUILabelAccess() {
		return pUILabel;
	}
	
	public ParserRule getUILabelRule() {
		return getUILabelAccess().getRule();
	}

	//Action returns mvc::Action:
	//	{mvc::Action} annotations+=Annotation? name=ID "{" ("preExecutionEvent" preExecutionEvent=[mvc::Event])?
	//	("postExecutionEvent" postExecutionEvent=[mvc::Event])? ("triggerEvents" "(" triggerEvents+=[mvc::Event] (","
	//	triggerEvents+=[mvc::Event])* ")")? "}";
	public ActionElements getActionAccess() {
		return pAction;
	}
	
	public ParserRule getActionRule() {
		return getActionAccess().getRule();
	}

	//ControllerView returns mvc::ControllerView:
	//	annotations+=Annotation? "view" view=[mvc::View] ("models" "(" models+=[mvc::Model] ("," models+=[mvc::Model])* ")")?
	//	";";
	public ControllerViewElements getControllerViewAccess() {
		return pControllerView;
	}
	
	public ParserRule getControllerViewRule() {
		return getControllerViewAccess().getRule();
	}

	//EventAction returns mvc::EventAction:
	//	annotations+=Annotation? "EventAction" "{" "action" action=[mvc::Action] ("events" "(" events+=[mvc::Event] (","
	//	events+=[mvc::Event])* ")")? "}";
	public EventActionElements getEventActionAccess() {
		return pEventAction;
	}
	
	public ParserRule getEventActionRule() {
		return getEventActionAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" . / * 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' * / | !("\\" | "\""))* "\"" | "\'" ("\\" .
	//	/ * 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' * / | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
