/*
 * generated by Xtext
 */
package co.edu.uniandes.csw.spl.dsl.ui.contentassist

import co.edu.uniandes.csw.spl.dsl.ui.contentassist.AbstractAnnotateitProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class AnnotateitProposalProvider extends AbstractAnnotateitProposalProvider {
}
