/*
 * generated by Xtext
 */
package co.edu.uniandes.csw.spl.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class AnnotateitUiModule extends co.edu.uniandes.csw.spl.dsl.ui.AbstractAnnotateitUiModule {
	public AnnotateitUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
