/*
 * generated by Xtext
 */
package co.edu.uniandes.csw.dsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class EntitiesRuntimeModule extends co.edu.uniandes.csw.dsl.AbstractEntitiesRuntimeModule {

}
