/**
 * generated by Xtext
 */
package co.edu.uniandes.csw.spl.dsl.validation;

import co.edu.uniandes.csw.spl.dsl.validation.AbstractAnnotateitValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class AnnotateitValidator extends AbstractAnnotateitValidator {
}
