/**
 * generated by Xtext
 */
package co.edu.uniandes.csw.spl.dsl.ui.quickfix;

import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#quickfixes
 */
@SuppressWarnings("all")
public class MVCDslQuickfixProvider extends DefaultQuickfixProvider {
}
