/**
 * generated by Xtext
 */
package co.edu.uniandes.csw.dsl.ui.contentassist;

import co.edu.uniandes.csw.dsl.ui.contentassist.AbstractComponentProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class ComponentProposalProvider extends AbstractComponentProposalProvider {
}
