/*
 * generated by Xtext
 */
package co.edu.uniandes.csw.dsl.ui.contentassist

import co.edu.uniandes.csw.dsl.ui.contentassist.AbstractEntitiesProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class EntitiesProposalProvider extends AbstractEntitiesProposalProvider {
}
